### ISSUE TITLE
get error window is not defined

### ISSUE THREAD

**Issue by morlz** [zerobias/telegram-mtproto#91]
using 
> node v8.4.0
> telegram-mtproto v3.2.9

get error `ReferenceError: window is not defined` on evry api call. What am I doing wrong?

src: in file `time-manager.js` on line `13` code: `if (!isNode) t += window.tsOffset || 0`
dist: in file `mtproto2-browser.js` on line `1302` code:  `if (!__WEBPACK_IMPORTED_MODULE_0_detect_node___default.a) t += window.tsOffset || 0;`

**Comment by goodmind** [comment]
why are you using mtproto2-browser.js ?

**Comment by morlz** [comment]
in nodejs

**Comment by goodmind** [comment]
hmm, it should be okay @zerobias

**Comment by zerobias** [comment]
@morlz 
Something going wrong on your side, because 3.2.9 even [doesn't contain](https://github.com/zerobias/telegram-mtproto/blob/feature/mtproto3/packages/telegram-mtproto/package.json#L99) file `mtproto2-browser` (moreover you still doesn't need it)

Try to clean up your project, e.g. remove node_modules and run `npm install` again
